//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swd.PlayCollector.DataNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionItem
    {
        public long Id { get; set; }
        public Nullable<long> COL_LOCId { get; set; }
        public Nullable<long> COL_THEId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
