//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swd.PlayCollector.DataNet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlayCollector : DbContext
    {
        public PlayCollector()
            : base("name=PlayCollector")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectionItem> CollectionItems { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
    }
}
