//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherConsole.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] clearsky_day {
            get {
                object obj = ResourceManager.GetObject("clearsky_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] clearsky_night {
            get {
                object obj = ResourceManager.GetObject("clearsky_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] clearsky_polartwilight {
            get {
                object obj = ResourceManager.GetObject("clearsky_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cloudy {
            get {
                object obj = ResourceManager.GetObject("cloudy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fair_day {
            get {
                object obj = ResourceManager.GetObject("fair_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fair_night {
            get {
                object obj = ResourceManager.GetObject("fair_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fair_polartwilight {
            get {
                object obj = ResourceManager.GetObject("fair_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fog {
            get {
                object obj = ResourceManager.GetObject("fog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavyrain {
            get {
                object obj = ResourceManager.GetObject("heavyrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavyrainandthunder {
            get {
                object obj = ResourceManager.GetObject("heavyrainandthunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavyrainshowers_day {
            get {
                object obj = ResourceManager.GetObject("heavyrainshowers_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavyrainshowers_night {
            get {
                object obj = ResourceManager.GetObject("heavyrainshowers_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavyrainshowers_polartwilight {
            get {
                object obj = ResourceManager.GetObject("heavyrainshowers_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavyrainshowersandthunder_day {
            get {
                object obj = ResourceManager.GetObject("heavyrainshowersandthunder_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavyrainshowersandthunder_night {
            get {
                object obj = ResourceManager.GetObject("heavyrainshowersandthunder_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavyrainshowersandthunder_polartwilight {
            get {
                object obj = ResourceManager.GetObject("heavyrainshowersandthunder_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysleet {
            get {
                object obj = ResourceManager.GetObject("heavysleet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysleetandthunder {
            get {
                object obj = ResourceManager.GetObject("heavysleetandthunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysleetshowers_day {
            get {
                object obj = ResourceManager.GetObject("heavysleetshowers_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysleetshowers_night {
            get {
                object obj = ResourceManager.GetObject("heavysleetshowers_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysleetshowers_polartwilight {
            get {
                object obj = ResourceManager.GetObject("heavysleetshowers_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysleetshowersandthunder_day {
            get {
                object obj = ResourceManager.GetObject("heavysleetshowersandthunder_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysleetshowersandthunder_night {
            get {
                object obj = ResourceManager.GetObject("heavysleetshowersandthunder_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysleetshowersandthunder_polartwilight {
            get {
                object obj = ResourceManager.GetObject("heavysleetshowersandthunder_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysnow {
            get {
                object obj = ResourceManager.GetObject("heavysnow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysnowandthunder {
            get {
                object obj = ResourceManager.GetObject("heavysnowandthunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysnowshowers_day {
            get {
                object obj = ResourceManager.GetObject("heavysnowshowers_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysnowshowers_night {
            get {
                object obj = ResourceManager.GetObject("heavysnowshowers_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysnowshowers_polartwilight {
            get {
                object obj = ResourceManager.GetObject("heavysnowshowers_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysnowshowersandthunder_day {
            get {
                object obj = ResourceManager.GetObject("heavysnowshowersandthunder_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysnowshowersandthunder_night {
            get {
                object obj = ResourceManager.GetObject("heavysnowshowersandthunder_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heavysnowshowersandthunder_polartwilight {
            get {
                object obj = ResourceManager.GetObject("heavysnowshowersandthunder_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightrain {
            get {
                object obj = ResourceManager.GetObject("lightrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightrainandthunder {
            get {
                object obj = ResourceManager.GetObject("lightrainandthunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightrainshowers_day {
            get {
                object obj = ResourceManager.GetObject("lightrainshowers_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightrainshowers_night {
            get {
                object obj = ResourceManager.GetObject("lightrainshowers_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightrainshowers_polartwilight {
            get {
                object obj = ResourceManager.GetObject("lightrainshowers_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightrainshowersandthunder_day {
            get {
                object obj = ResourceManager.GetObject("lightrainshowersandthunder_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightrainshowersandthunder_night {
            get {
                object obj = ResourceManager.GetObject("lightrainshowersandthunder_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightrainshowersandthunder_polartwilight {
            get {
                object obj = ResourceManager.GetObject("lightrainshowersandthunder_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsleet {
            get {
                object obj = ResourceManager.GetObject("lightsleet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsleetandthunder {
            get {
                object obj = ResourceManager.GetObject("lightsleetandthunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsleetshowers_day {
            get {
                object obj = ResourceManager.GetObject("lightsleetshowers_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsleetshowers_night {
            get {
                object obj = ResourceManager.GetObject("lightsleetshowers_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsleetshowers_polartwilight {
            get {
                object obj = ResourceManager.GetObject("lightsleetshowers_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsnow {
            get {
                object obj = ResourceManager.GetObject("lightsnow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsnowandthunder {
            get {
                object obj = ResourceManager.GetObject("lightsnowandthunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsnowshowers_day {
            get {
                object obj = ResourceManager.GetObject("lightsnowshowers_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsnowshowers_night {
            get {
                object obj = ResourceManager.GetObject("lightsnowshowers_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightsnowshowers_polartwilight {
            get {
                object obj = ResourceManager.GetObject("lightsnowshowers_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightssleetshowersandthunder_day {
            get {
                object obj = ResourceManager.GetObject("lightssleetshowersandthunder_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightssleetshowersandthunder_night {
            get {
                object obj = ResourceManager.GetObject("lightssleetshowersandthunder_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightssleetshowersandthunder_polartwilight {
            get {
                object obj = ResourceManager.GetObject("lightssleetshowersandthunder_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightssnowshowersandthunder_day {
            get {
                object obj = ResourceManager.GetObject("lightssnowshowersandthunder_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightssnowshowersandthunder_night {
            get {
                object obj = ResourceManager.GetObject("lightssnowshowersandthunder_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightssnowshowersandthunder_polartwilight {
            get {
                object obj = ResourceManager.GetObject("lightssnowshowersandthunder_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] partlycloudy_day {
            get {
                object obj = ResourceManager.GetObject("partlycloudy_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] partlycloudy_night {
            get {
                object obj = ResourceManager.GetObject("partlycloudy_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] partlycloudy_polartwilight {
            get {
                object obj = ResourceManager.GetObject("partlycloudy_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rain {
            get {
                object obj = ResourceManager.GetObject("rain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rainandthunder {
            get {
                object obj = ResourceManager.GetObject("rainandthunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rainshowers_day {
            get {
                object obj = ResourceManager.GetObject("rainshowers_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rainshowers_night {
            get {
                object obj = ResourceManager.GetObject("rainshowers_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rainshowers_polartwilight {
            get {
                object obj = ResourceManager.GetObject("rainshowers_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rainshowersandthunder_day {
            get {
                object obj = ResourceManager.GetObject("rainshowersandthunder_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rainshowersandthunder_night {
            get {
                object obj = ResourceManager.GetObject("rainshowersandthunder_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rainshowersandthunder_polartwilight {
            get {
                object obj = ResourceManager.GetObject("rainshowersandthunder_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sleet {
            get {
                object obj = ResourceManager.GetObject("sleet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sleetandthunder {
            get {
                object obj = ResourceManager.GetObject("sleetandthunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sleetshowers_day {
            get {
                object obj = ResourceManager.GetObject("sleetshowers_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sleetshowers_night {
            get {
                object obj = ResourceManager.GetObject("sleetshowers_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sleetshowers_polartwilight {
            get {
                object obj = ResourceManager.GetObject("sleetshowers_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sleetshowersandthunder_day {
            get {
                object obj = ResourceManager.GetObject("sleetshowersandthunder_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sleetshowersandthunder_night {
            get {
                object obj = ResourceManager.GetObject("sleetshowersandthunder_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sleetshowersandthunder_polartwilight {
            get {
                object obj = ResourceManager.GetObject("sleetshowersandthunder_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snow {
            get {
                object obj = ResourceManager.GetObject("snow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowandthunder {
            get {
                object obj = ResourceManager.GetObject("snowandthunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowshowers_day {
            get {
                object obj = ResourceManager.GetObject("snowshowers_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowshowers_night {
            get {
                object obj = ResourceManager.GetObject("snowshowers_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowshowers_polartwilight {
            get {
                object obj = ResourceManager.GetObject("snowshowers_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowshowersandthunder_day {
            get {
                object obj = ResourceManager.GetObject("snowshowersandthunder_day", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowshowersandthunder_night {
            get {
                object obj = ResourceManager.GetObject("snowshowersandthunder_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snowshowersandthunder_polartwilight {
            get {
                object obj = ResourceManager.GetObject("snowshowersandthunder_polartwilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
